ARG GO_VERSION=alpine
ARG BASE=golang:1.21.7-alpine3.19

FROM ${BASE} as builder

RUN apk update \
 && apk add --no-cache \
    linux-headers \
    gcc \
    libtool \
    openssl-dev \
    libffi \
    tini \
    git \
    'su-exec>=0.2' \
 && apk add --no-cache --virtual .build_deps build-base libffi-dev

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN addgroup -g 502 -S eodata \
 && adduser -u 502 -S -G eodata eodata \
 && mkdir -p /app/eodata/logs \
 && chown -R eodata:eodata /app/eodata

# Move to working directory
WORKDIR /app/eodata

# Download dependency using go mod
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY --chown=eodata:eodata . .

RUN platform=arm64 && \
    if [ $(uname -m) = x86_64 ]; then platform=amd64; fi && \
    make build-oprcli-${platform} && \
    mv ./bin/oprcli-${platform} ./bin/oprcli 
RUN chown eodata:eodata ./bin/oprcli

FROM golang:${GO_VERSION}

RUN apk update \
 && apk add --no-cache \
    linux-headers \
    gcc \
    libtool \
    openssl-dev \
    libffi \
    tini \
    git \
    'su-exec>=0.2' \
 && apk add --no-cache --virtual .build_deps build-base libffi-dev

# add our user and group first to make sure their IDs get assigned consistently, regardless of whatever dependencies get added
RUN addgroup -g 502 -S eodata \
 && adduser -u 502 -S -G eodata eodata \
 && mkdir -p /app/eodata/logs \
 && mkdir -p /app/eodata/datadir \
 && chown -R eodata:eodata /app/eodata

# Move to working directory
WORKDIR /app/eodata

COPY --from=builder /app/eodata/bin/oprcli /app/eodata/bin/oprcli

COPY docker-entrypoint-oprcli.sh /usr/local/bin/

ENV PATH="/app/eodata/bin:${PATH}"

ENTRYPOINT ["/sbin/tini", "--", "/bin/sh", "/usr/local/bin/docker-entrypoint-oprcli.sh"]